name: bakery_shop_fakeapi
description: Bakery shop demo using FakeStore API + Provider
publish_to: "none"

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
