name: bakery_shop_fakeapi

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true